-- =====================================================================
-- PGW Support Portal — Horizon slot reservations, queue-order
-- correction, and upload precondition 3               (Brief 38, rev. 2)
-- Run AFTER pgw_horizon_seed_2320_38a.sql, in the Supabase SQL Editor.
-- Safe to re-run (idempotent throughout).
-- =====================================================================
-- Migration 38 was built from an earlier revision of the brief. The
-- consolidated brief adds a concept 38 does not have at all -- RESERVED
-- SLOTS -- and reverses two decisions 38 shipped. This file closes that
-- gap. It changes no data; the per-store seed lives in 39a.
--
-- WHAT A RESERVATION IS, AND WHY IT IS NOT A TECHNICIAN.
-- Horizon addresses 20 slots per shop and every slot must account for
-- the labor sales written into it. Two categories of labor sales are
-- generated by people who are not technicians on the roster:
--
--   front_staff  every store, exactly one. Front-of-house staff
--                generate labor sales with NO ASSOCIATED LABOR COST.
--                The slot lets Horizon carry that labor sales figure
--                without attributing uncosted hours to a technician.
--
--   gs_techs     SpeeDee only, exactly one. Pooled general service
--                work. GS TECHS DO CARRY LABOR COST.
--
-- That cost asymmetry is the whole reason these are two kinds and not
-- one boolean: one path writes uncosted labor sales, the other writes
-- costed work. Collapsing them writes cost against a slot that has none
-- or drops cost from a slot that has some -- either way a silent wrong
-- number in an external system, which is the failure mode migration 38
-- exists to prevent. A store may hold one of each; the partial unique
-- index enforces one PER KIND, not one per store.
--
-- WHAT ELSE CHANGES, AND WHY EACH IS A REVERSAL AND NOT A TWEAK:
--
--   1. next_horizon_slot() ordered `last_released_at asc nulls first`.
--      It must be `nulls last`. See section 3.
--
--   2. Migration 38 added location_horizon_slots_occupant_key, a
--      one-employee-per-slot unique index. The consolidated brief says
--      explicitly not to add it yet. See section 2.
--
-- NOT IN SCOPE HERE: the 38 shop numbers, the per-store reservations,
-- and the 464-row slot-state import. Those are data, and they are in
-- pgw_horizon_reservations_seed_39a.sql. Run this file first -- 39a
-- calls reserve_horizon_slot(), which does not exist until this file
-- has run.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 0. PREFLIGHT
--    Section 2 drops a unique index. Dropping one can never fail on
--    existing data, so there is nothing to guard there. What IS worth
--    reporting is whether any duplicate occupancy already exists, so
--    that a row this migration stops rejecting is a deliberate seed
--    (3831, section 2) rather than something that crept in unnoticed.
--    Reports; does not raise.
-- ---------------------------------------------------------------------
do $$
declare
  v_dupes int;
begin
  select count(*) into v_dupes
  from (
    select location_id, current_technician_id
    from public.location_horizon_slots
    where current_technician_id is not null
    group by location_id, current_technician_id
    having count(*) > 1
  ) d;

  if v_dupes > 0 then
    raise notice
      'PREFLIGHT: % technician(s) already hold more than one Horizon slot at a store. Expected 0 before 39a; 39a seeds exactly one such case (store 3831, Carlos Moran, slots 8 and 12).',
      v_dupes;
  else
    raise notice 'PREFLIGHT: no duplicate slot occupancy. OK.';
  end if;
end
$$;


-- ---------------------------------------------------------------------
-- 1. RESERVATION COLUMNS
-- ---------------------------------------------------------------------

-- 1.1 The kind enum. An enum rather than a text check because the two
--     values differ in COST SEMANTICS, not in wording -- a third value
--     is a decision about how labor cost is written, and it should
--     require a migration to add rather than passing a check constraint
--     because someone typed it.
do $$
begin
  if not exists (
    select 1 from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'horizon_reservation_kind' and n.nspname = 'public'
  ) then
    create type public.horizon_reservation_kind as enum ('front_staff', 'gs_techs');
  end if;
end
$$;

-- 1.2 Columns.
--     reservation_label is free text and carries only the store's own
--     wording for its own screens. It is NOT how a reservation is
--     found -- see the comment on section 5.
alter table public.location_horizon_slots
  add column if not exists is_reserved       boolean not null default false,
  add column if not exists reservation_kind  public.horizon_reservation_kind null,
  add column if not exists reservation_label text null;

-- 1.3 A reserved slot holds no technician, and a reservation always has
--     a kind. Dropped and re-added rather than `if not exists` so a
--     re-run cannot leave an older definition in place.
alter table public.location_horizon_slots
  drop constraint if exists lhs_reserved_unoccupied;
alter table public.location_horizon_slots
  add constraint lhs_reserved_unoccupied
  check (not (is_reserved and current_technician_id is not null));

alter table public.location_horizon_slots
  drop constraint if exists lhs_reserved_has_kind;
alter table public.location_horizon_slots
  add constraint lhs_reserved_has_kind
  check (is_reserved = (reservation_kind is not null));

-- 1.4 One reservation PER KIND per location. A SpeeDee store legitimately
--     holds a front_staff AND a gs_techs reservation, so this is not a
--     one-per-store index.
create unique index if not exists location_horizon_slots_one_per_kind
  on public.location_horizon_slots (location_id, reservation_kind)
  where is_reserved = true;

comment on column public.location_horizon_slots.is_reserved is
  'Slot is held for a non-technician labor-sales category and is skipped by next_horizon_slot(). Never simultaneously occupied.';
comment on column public.location_horizon_slots.reservation_kind is
  'front_staff = uncosted front-of-house labor sales, every store, exactly one. gs_techs = SpeeDee pooled general service, WHICH DOES CARRY LABOR COST. The cost asymmetry is why these are two kinds and not one flag.';
comment on column public.location_horizon_slots.reservation_label is
  'Display wording only. NEVER match on this to locate a reservation -- source wording varies (MN & SA, MANAGER, Frontshop, midas store). Locate by reservation_kind.';


-- ---------------------------------------------------------------------
-- 2. REVERSAL: DROP THE ONE-EMPLOYEE-PER-SLOT INDEX
--
--    Migration 38 added location_horizon_slots_occupant_key on the
--    reasoning that it mirrors migration 29's
--    tech_slots_one_slot_per_employee. The consolidated brief says not
--    to add it in this round, and the reason is concrete: store 3831
--    has Carlos Moran in slots 8 AND 12 in Horizon today. That is under
--    investigation and the brief requires it seeded AS-IS and flagged.
--
--    The index would reject that seed. Rejecting it does not fix 3831 --
--    it just means the portal's picture of 3831 silently differs from
--    Horizon's, which is the class of drift this whole area of the
--    schema exists to prevent. Record reality, flag it, resolve it,
--    THEN constrain it.
--
--    THE ASSIGNMENT PATH STILL REFUSES A SECOND SLOT. The readable
--    guard inside assign_horizon_slot() (section 4) is untouched, so no
--    NEW duplicate can be created through the normal path. Only the
--    seeding path, which is admin-only and deliberate, can produce one.
--
--    FOLLOW-UP, not forgotten: re-add this index once 3831 is resolved.
--      create unique index location_horizon_slots_occupant_key
--        on public.location_horizon_slots (location_id, current_technician_id)
--        where current_technician_id is not null;
--
--    The non-unique lookup index is kept -- it serves the view joins and
--    was never the constraint.
-- ---------------------------------------------------------------------
drop index if exists public.location_horizon_slots_occupant_key;


-- ---------------------------------------------------------------------
-- 3. REVERSAL: nulls first -> nulls last, AND SKIP RESERVED SLOTS
--
--    Migration 38 ordered freed slots `last_released_at asc nulls
--    first`, reading a null as "oldest, therefore safest to reuse".
--    That reading is backwards.
--
--    A null last_released_at on a freed slot does not mean the slot was
--    vacated long ago. It means THE VACATE DATE COULD NOT BE
--    RECONSTRUCTED -- 94 stale slots from the Horizon drafts are in
--    exactly this state, plus every placeholder and blank below slot 12.
--    If we do not know when a slot was vacated, we do not know how much
--    technician history is sitting in it. Under `nulls first` those are
--    the slots the queue hands out FIRST, which is precisely inverted:
--    unknown risk is being treated as no risk.
--
--    `nulls last` reuses them last, after every slot whose history depth
--    we can actually reason about. The never-used group is unaffected
--    either way -- it sorts first on ever_used before last_released_at
--    is ever consulted.
--
--    The reserved filter is the other half: a reserved slot is not free
--    capacity, it is capacity already spoken for by a labor-sales
--    category. Handing it to a technician would write costed technician
--    hours over front-of-house sales.
-- ---------------------------------------------------------------------
create or replace function public.next_horizon_slot(p_location_id uuid)
returns smallint
language sql stable
set search_path = public, pg_temp
as $fn$
  select slot_number
  from public.location_horizon_slots
  where location_id = p_location_id
    and current_technician_id is null
    and is_reserved = false
  order by ever_used asc,                    -- never-used before freed
           last_released_at asc nulls last,  -- among freed, oldest first; unknown LAST
           slot_number asc                   -- deterministic tiebreak
  limit 1
$fn$;


-- ---------------------------------------------------------------------
-- 4. ASSIGNMENT — the full-store message must distinguish occupied
--    from reserved
--
--    With reservations in play, "all 20 slots are occupied" can now be
--    false while assignment still fails: a store can have 18 occupied
--    and 2 reserved. A manager told the store is full, who can count 18
--    technicians, has been given a message that contradicts what he can
--    see, and the actual remedy differs -- release a technician, or
--    clear a reservation. Name both counts.
--
--    Everything else here is migration 38's body unchanged, including
--    the second-slot guard, which section 2 deliberately keeps.
-- ---------------------------------------------------------------------
create or replace function public.assign_horizon_slot(
  p_location_id   uuid,
  p_technician_id uuid
) returns smallint
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_slot smallint;
  v_occ  int;
  v_res  int;
begin
  if public.current_user_role() not in ('admin','master') then
    raise exception 'Only an admin can assign a Horizon slot' using errcode = '42501';
  end if;
  if not public.can_access_location(p_location_id) then
    raise exception 'not authorized for that location' using errcode = '42501';
  end if;
  if p_technician_id is null then
    raise exception 'a technician is required' using errcode = '22023';
  end if;

  -- Kept deliberately: section 2 drops the INDEX, not this guard. No new
  -- duplicate occupancy can be created through the assignment path.
  if exists (
    select 1 from public.location_horizon_slots
     where location_id = p_location_id
       and current_technician_id = p_technician_id
  ) then
    raise exception 'That technician already holds a Horizon slot at this store'
      using errcode = '23505';
  end if;

  select public.next_horizon_slot(p_location_id) into v_slot;

  if v_slot is null then
    select count(*) filter (where current_technician_id is not null),
           count(*) filter (where is_reserved)
      into v_occ, v_res
      from public.location_horizon_slots
     where location_id = p_location_id;

    raise exception
      'All 20 Horizon slots at location % are unavailable (% occupied, % reserved). Release a technician or clear a reservation before assigning.',
      p_location_id, v_occ, v_res
      using errcode = 'P0001';
  end if;

  update public.location_horizon_slots
     set current_technician_id = p_technician_id,
         ever_used             = true,
         last_released_at      = null
   where location_id = p_location_id and slot_number = v_slot;

  return v_slot;
end
$fn$;


-- ---------------------------------------------------------------------
-- 5. RESERVE AND CLEAR
--
--    RESERVATIONS ARE NOT RELEASES. Clearing a reservation must not set
--    last_released_at: no technician ever held the slot, so there is no
--    history at risk and no queue position has been earned. A never-used
--    slot that is reserved and later cleared returns to the never-used
--    group untouched, because reserving never sets ever_used.
--
--    THE RESERVED SLOT IS LOCATED BY reservation_kind, NEVER BY SLOT
--    NUMBER. Front Staff sits at slot 20 at nineteen stores, slot 6 at
--    seven, slot 2 at three, and slots 5, 7, 9 and 12 elsewhere. Any
--    code that looks up a constant is wrong at most stores, and wrong
--    quietly -- it writes front-of-house labor sales into whichever
--    technician happens to hold that number.
-- ---------------------------------------------------------------------
create or replace function public.reserve_horizon_slot(
  p_location_id uuid,
  p_slot_number smallint,
  p_kind        public.horizon_reservation_kind,
  p_label       text
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_brand    text;
  v_occupant uuid;
begin
  if public.current_user_role() not in ('admin','master') then
    raise exception 'Only an admin can reserve a Horizon slot' using errcode = '42501';
  end if;
  if not public.can_access_location(p_location_id) then
    raise exception 'not authorized for that location' using errcode = '42501';
  end if;

  select l.brand into v_brand from public.locations l where l.id = p_location_id;
  if not found then
    raise exception 'location % not found', p_location_id using errcode = '42704';
  end if;

  -- gs_techs is the SpeeDee pooled model, and it is the kind that
  -- CARRIES LABOR COST. Granting one at a Midas store would write costed
  -- general-service hours at a store that has no such pool -- cost
  -- against sales that were never generated that way. If the pooled
  -- model is ever extended to Midas, this is a one-line change, not a
  -- schema change; that is why it is a function check and not a
  -- constraint.
  if p_kind = 'gs_techs' and v_brand <> 'speedee' then
    raise exception
      'A gs_techs reservation is the SpeeDee pooled general-service model and carries labor cost. Location % is brand %.',
      p_location_id, v_brand
      using errcode = 'P0001';
  end if;

  select current_technician_id into v_occupant
    from public.location_horizon_slots
   where location_id = p_location_id and slot_number = p_slot_number;

  if not found then
    raise exception 'Location % has no Horizon slot %', p_location_id, p_slot_number
      using errcode = '42704';
  end if;

  -- Readable message ahead of lhs_reserved_unoccupied firing. Reserving
  -- over a technician is never right: either the reservation belongs
  -- elsewhere or the technician must be released deliberately first,
  -- and release is the irreversible step (section 3.3 of migration 38).
  if v_occupant is not null then
    raise exception
      'Horizon slot % at location % is held by a technician. Release the technician deliberately before reserving the slot.',
      p_slot_number, p_location_id
      using errcode = 'P0001';
  end if;

  update public.location_horizon_slots
     set is_reserved           = true,
         reservation_kind      = p_kind,
         reservation_label     = p_label,
         current_technician_id = null
   where location_id = p_location_id and slot_number = p_slot_number;
end
$fn$;

-- 5.1 Clear. Note what is NOT touched: last_released_at and ever_used.
create or replace function public.clear_horizon_reservation(
  p_location_id uuid,
  p_slot_number smallint
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
begin
  if public.current_user_role() not in ('admin','master') then
    raise exception 'Only an admin can clear a Horizon reservation' using errcode = '42501';
  end if;
  if not public.can_access_location(p_location_id) then
    raise exception 'not authorized for that location' using errcode = '42501';
  end if;

  update public.location_horizon_slots
     set is_reserved       = false,
         reservation_kind  = null,
         reservation_label = null
   where location_id = p_location_id
     and slot_number  = p_slot_number
     and is_reserved  = true;
end
$fn$;


-- ---------------------------------------------------------------------
-- 6. SEEDING CLEARS RESERVATION STATE
--
--    seed_horizon_slot() imports Horizon's existing picture of a slot
--    as-is. If the portal thinks slot 6 is Front Staff and Horizon shows
--    a technician there, Horizon is what the upload will overwrite, so
--    the reservation must come off. Migration 38's version predates
--    reservations and would leave a stale one behind, which
--    lhs_reserved_unoccupied would then reject on an occupied seed.
--
--    ever_used = true is still set unconditionally, INCLUDING for a
--    vacated slot with no occupant. That remains the entire reason the
--    seeding path is separate from the assignment path.
-- ---------------------------------------------------------------------
create or replace function public.seed_horizon_slot(
  p_location_id   uuid,
  p_slot_number   smallint,
  p_technician_id uuid,        -- null for a vacated slot
  p_released_at   timestamptz  -- null when occupied
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
begin
  if public.current_user_role() not in ('admin','master') then
    raise exception 'Only an admin can seed Horizon slots' using errcode = '42501';
  end if;
  if not public.can_access_location(p_location_id) then
    raise exception 'not authorized for that location' using errcode = '42501';
  end if;

  update public.location_horizon_slots
     set current_technician_id = p_technician_id,
         ever_used             = true,
         is_reserved           = false,
         reservation_kind      = null,
         reservation_label     = null,
         last_released_at      = case when p_technician_id is null then p_released_at else null end
   where location_id = p_location_id and slot_number = p_slot_number;
end
$fn$;

revoke all on function public.reserve_horizon_slot(uuid, smallint, public.horizon_reservation_kind, text) from public, anon;
revoke all on function public.clear_horizon_reservation(uuid, smallint) from public, anon;
grant execute on function public.reserve_horizon_slot(uuid, smallint, public.horizon_reservation_kind, text) to authenticated;
grant execute on function public.clear_horizon_reservation(uuid, smallint) to authenticated;


-- ---------------------------------------------------------------------
-- 7. RESERVATION LOOKUP VIEW
--    Backs the "locate by kind, never by number" rule with something
--    callers can actually use, so no screen or job has a reason to
--    hardcode a slot number.
-- ---------------------------------------------------------------------
create or replace view public.horizon_reserved_slots
  with (security_invoker = true) as
select s.location_id,
       s.slot_number,
       s.reservation_kind,
       s.reservation_label
from public.location_horizon_slots s
where s.is_reserved = true;

comment on view public.horizon_reserved_slots is
  'Reserved Horizon slots by kind. The upload resolves the front_staff slot THROUGH THIS VIEW, filtering on reservation_kind. Front Staff is at slot 20 at some stores, 6 at others, 2 at others -- never assume a number.';


-- ---------------------------------------------------------------------
-- 8. UPLOAD PRECONDITION 3 — exactly one front_staff reservation
--
--    Uploading without a Front Staff slot sends front-of-house labor
--    sales either nowhere or into a technician's slot. Both are silent
--    wrong numbers rather than visible failures, which is why this is a
--    precondition and not a warning.
--
--    "Exactly one", not "at least one": the partial unique index makes
--    two impossible, so a count other than 1 here means zero, and the
--    count is checked rather than existence so the message can say which.
--
--    THE RETURN SIGNATURE GAINS front_staff_slot. This is the section 8
--    bridge made structural: the transport aggregates front-staff labor
--    sales on the portal side (tech_slots.is_manager_or_sa) and writes
--    the total into this slot number, with NO LABOR COST -- zero cost
--    against non-zero labor sales is the intended behaviour and the
--    reason the slot exists. Returning the number from the authorised
--    target means the transport never has a reason to look one up, and
--    therefore never has a reason to hardcode one. On refusal it comes
--    back null alongside shop_number, for the same reason: there must be
--    nothing usable in a refused verdict.
--
--    Drop-then-create because the return type changes. No caller exists
--    today -- the transport is still out of scope -- so this is safe now
--    and would not be later.
-- ---------------------------------------------------------------------
drop function if exists public.horizon_upload_target(uuid, text);

create or replace function public.horizon_upload_target(
  p_location_id   uuid,
  p_intended_shop text default null
)
returns table (shop_number text, authorized boolean, front_staff_slot smallint, reason text)
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_shop     text;
  v_sandbox  boolean;
  v_conflict text;
  v_reason   text;
  v_fs_slot  smallint;
  v_fs_count int;
begin
  if public.current_user_role() not in ('admin','master') then
    raise exception 'Only an admin can upload to Horizon' using errcode = '42501';
  end if;

  select l.horizon_shop_number, l.is_sandbox
    into v_shop, v_sandbox
    from public.locations l
   where l.id = p_location_id;

  if not found then
    raise exception 'location % not found', p_location_id using errcode = '42704';
  end if;

  select count(*), min(s.slot_number)
    into v_fs_count, v_fs_slot
    from public.location_horizon_slots s
   where s.location_id = p_location_id
     and s.is_reserved = true
     and s.reservation_kind = 'front_staff';

  -- (3) refuse null
  if v_shop is null then
    v_reason := 'Location has no Horizon shop number, so it cannot upload. Load its credentials first.';

  -- (1) the caller may assert, never override
  elsif p_intended_shop is not null and p_intended_shop <> v_shop then
    v_reason := format('Horizon shop number mismatch: caller asserted %L but the location resolves to %L.',
                       p_intended_shop, v_shop);

  else
    -- (2) assert the pairing
    select string_agg(l2.id::text, ', ') into v_conflict
      from public.locations l2
     where l2.horizon_shop_number = v_shop
       and l2.is_sandbox is distinct from v_sandbox;
    if v_conflict is not null then
      v_reason := format('Horizon sandbox pairing violated: shop %L is also claimed by location(s) %s with a different sandbox flag.',
                         v_shop, v_conflict);

    -- (4) NEW: a Front Staff slot must exist to receive uncosted
    --     front-of-house labor sales.
    elsif v_fs_count <> 1 then
      v_reason := format('Location has %s Front Staff reservations, expected exactly 1. Front-of-house labor sales have nowhere to go; reserve a Front Staff slot before uploading.',
                         v_fs_count);
    end if;
  end if;

  insert into public.horizon_upload_log
    (location_id, shop_number, is_sandbox, outcome, detail, attempted_by)
  values
    (p_location_id, v_shop, v_sandbox,
     case when v_reason is null then 'authorized' else 'refused' end,
     v_reason, auth.uid());

  -- On refusal nothing usable comes back -- neither the shop to
  -- transmit to nor the slot to write into.
  shop_number      := case when v_reason is null then v_shop else null end;
  authorized       := v_reason is null;
  front_staff_slot := case when v_reason is null then v_fs_slot else null end;
  reason           := v_reason;
  return next;
end
$fn$;

revoke all on function public.horizon_upload_target(uuid, text) from public, anon;
grant execute on function public.horizon_upload_target(uuid, text) to authenticated;


-- =====================================================================
-- VERIFY — run in order, in the SQL Editor.
-- Verification numbering follows the consolidated brief section 10.
--
--   Setup: pick any real store to experiment on, and put it back after.
--     -- select id, store_number, brand from public.locations
--     --  where store_number = '3303';
--
--  [14] A reserved slot is never returned by next_horizon_slot():
--         select public.reserve_horizon_slot(:loc, 1::smallint, 'front_staff', 'Front Staff');
--         select public.next_horizon_slot(:loc);      -- NOT 1
--
--  [15] The check constraint rejects occupying a reserved slot:
--         update public.location_horizon_slots
--            set current_technician_id = (select id from public.employees limit 1)
--          where location_id = :loc and slot_number = 1;
--         -- ERROR: lhs_reserved_unoccupied
--
--  [16] A SpeeDee store holds both kinds at once (use a speedee loc):
--         select public.reserve_horizon_slot(:sd_loc, 20::smallint, 'front_staff', 'Front Staff');
--         select public.reserve_horizon_slot(:sd_loc,  5::smallint, 'gs_techs',    'GS Techs');
--         select slot_number, reservation_kind from public.horizon_reserved_slots
--          where location_id = :sd_loc;             -- two rows, no error
--
--  [16a] gs_techs is refused at a Midas store:
--         select public.reserve_horizon_slot(:midas_loc, 5::smallint, 'gs_techs', 'GS');
--         -- ERROR naming the brand
--
--  [17] A second front_staff at one location is rejected:
--         select public.reserve_horizon_slot(:loc, 7::smallint, 'front_staff', 'Front Staff');
--         -- ERROR: location_horizon_slots_one_per_kind
--
--  [18] Clearing does not set last_released_at, and a never-used slot
--       returns to the never-used group:
--         select ever_used, last_released_at from public.location_horizon_slots
--          where location_id = :loc and slot_number = 1;   -- false, null
--         select public.clear_horizon_reservation(:loc, 1::smallint);
--         select ever_used, last_released_at, is_reserved
--           from public.location_horizon_slots
--          where location_id = :loc and slot_number = 1;   -- false, null, false
--         select public.next_horizon_slot(:loc);           -- 1 is eligible again
--
--  [10] Unknown dates sort LAST (this is the reversal in section 3).
--       On a scratch location with slots 1-20 all ever_used and free,
--       set three release dates and leave one null:
--         update public.location_horizon_slots set ever_used = true,
--                current_technician_id = null, last_released_at = null
--          where location_id = :loc;
--         update public.location_horizon_slots set last_released_at = '2024-01-01'
--          where location_id = :loc and slot_number = 9;
--         update public.location_horizon_slots set last_released_at = '2025-01-01'
--          where location_id = :loc and slot_number = 3;
--         -- slot 5 stays null
--         select slot_number from public.location_horizon_slots
--          where location_id = :loc and current_technician_id is null
--            and is_reserved = false
--          order by ever_used, last_released_at nulls last, slot_number
--          limit 4;
--       Expect 9, then 3, then the null-dated slots by number -- the
--       null-dated slot must NOT come first. Before this migration it did.
--
--  [12] Full store distinguishes occupied from reserved. Occupy 18 and
--       reserve 2, then assign a 21st:
--         select public.assign_horizon_slot(:loc, :some_tech);
--         -- ERROR '... (18 occupied, 2 reserved). Release a technician
--         --        or clear a reservation before assigning.'
--
--  [29] Upload precondition 3. On a location with no front_staff row:
--         select * from public.horizon_upload_target(:loc);
--         -- authorized false, shop_number null, front_staff_slot null,
--         -- reason naming 0 Front Staff reservations.
--       Then reserve one and re-run: authorized true and front_staff_slot
--       is the reserved number, NOT a constant.
--         select * from public.horizon_upload_log
--          where location_id = :loc order by attempted_at desc limit 2;
--       Both attempts logged -- the refusal too.
--
--  [26-28] Migration 38's guards are unchanged and must still hold.
--       Re-run those three cases from pgw_horizon_slots_38.sql; the only
--       difference is the extra output column.
--
--  Section 2 regression -- the index is gone and the guard is not:
--         select indexname from pg_indexes
--          where tablename = 'location_horizon_slots';
--       Expect location_horizon_slots_pkey,
--              location_horizon_slots_occupant_idx,
--              location_horizon_slots_one_per_kind.
--       NOT location_horizon_slots_occupant_key.
--       Then confirm the assignment path still refuses a second slot:
--         select public.assign_horizon_slot(:loc, :tech_who_already_has_one);
--         -- ERROR 'That technician already holds a Horizon slot at this store'
--
--   [4] tech_slots is untouched, as in migration 38:
--         select count(*) from public.tech_slots;             -- 9 per store
--         select prosrc from pg_proc where proname = 'tech_reassign_slot';
--
--   Cleanup: undo anything reserved or released during the checks above.
--     select public.clear_horizon_reservation(:loc, 1::smallint);
-- =====================================================================
