-- =====================================================================
-- PGW Support Portal — migration 68: the Home Office (#1515)
-- =====================================================================
-- Asked for by the user 2026-09-25: "a 'home office' store ... does not
-- produce revenue but handles everything on the back end."
--
-- DECISIONS (user, 2026-09-25):
--   * It holds corporate staff, runs Payroll and the Employee Schedule,
--     and can have its own logins (role 'store' pointed at it).
--   * Store number 1515 — ADP's "Corporate #1515" department, so a later
--     census load lines up by number.
--   * OUTSIDE every district. can_access_location() therefore lets only
--     admin/master (and logins assigned to it) see it; district and
--     regional managers never do. No change to that function.
--   * A new 'Office' position, valid ONLY at the Home Office.
--   * EXCLUDED from company payroll % and every other revenue rollup.
--     Its payroll appears on its own Payroll page and nowhere else.
--   * NOT in the Company Directory (not chosen).
--
-- WHY A NEW FLAG AND NOT is_sandbox. is_sandbox hides a location from
-- store/district/regional users and marks it as fake data; the Home
-- Office is real and must be reachable by its own logins. Migration 38
-- also says sandbox must never be overloaded with a second meaning.
--
-- WHY brand STAYS 'midas'. brand is NOT NULL with a two-value check
-- repeated on four tables. The Home Office uses the Midas payroll
-- engine (hours, hourly/OT, salary, bonus) — the tech/sales columns are
-- hidden by the frontend — so a third brand value would buy nothing but
-- a wider blast radius. is_home_office, not brand, is what every
-- decision below keys off.
--
-- SALARIED OFFICE STAFF. Salary keys off employees.is_store_manager
-- (migration 32), which was limited to ONE position='manager' row per
-- location. Office staff are often salaried, so the check now also
-- allows position 'office', and the one-per-location index is narrowed
-- to managers. Pay math (SQL + lib/payrollMath.js) is unchanged. The
-- column name is historical; the UI labels it "Salaried" for office rows.
--
-- ROLLUPS. Every company scope site already reads
--   where public.can_access_location(l.id) and l.is_sandbox = false
-- and now reads
--   ... and l.is_sandbox = false and not l.is_home_office
-- The eight functions below are the SHIPPED bodies with only that
-- predicate spliced in (generated by build68.mjs, one asserted match
-- count per function). Single-store readers (payroll_pct_summary etc.)
-- are untouched: the Home Office's own Payroll page still works.
--
-- Re-runnable.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. THE FLAG
-- ---------------------------------------------------------------------
alter table public.locations
  add column if not exists is_home_office boolean not null default false;

comment on column public.locations.is_home_office is
  'The non-revenue Home Office (migration 68). Holds corporate staff, payroll and schedule; excluded from every revenue/payroll rollup, from the directory, and from Horizon. At most one.';

create unique index if not exists locations_one_home_office
  on public.locations ((true)) where is_home_office;

alter table public.locations drop constraint if exists locations_home_office_not_sandbox;
alter table public.locations add constraint locations_home_office_not_sandbox
  check (not (is_home_office and is_sandbox));

-- The Home Office never uploads to Horizon. horizon_upload_target()
-- already refuses a NULL shop number; this keeps it NULL.
alter table public.locations drop constraint if exists locations_home_office_no_horizon;
alter table public.locations add constraint locations_home_office_no_horizon
  check (not is_home_office or horizon_shop_number is null);


-- ---------------------------------------------------------------------
-- 2. NO HORIZON SLOTS FOR THE HOME OFFICE
--    Same function as migration 38, plus the one skip.
-- ---------------------------------------------------------------------
create or replace function public.provision_horizon_slots()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
begin
  if new.is_home_office then
    return new;
  end if;
  insert into public.location_horizon_slots (location_id, slot_number)
  select new.id, s.n from generate_series(1, 20) as s(n)
  on conflict (location_id, slot_number) do nothing;
  return new;
end
$fn$;


-- ---------------------------------------------------------------------
-- 3. THE LOCATION
--    Idempotent on store_number (partial unique index from migration 38).
--    No district, no address, no phone — admins can fill details later.
-- ---------------------------------------------------------------------
insert into public.locations (name, store_number, brand, district_id, is_home_office)
select 'Home Office', '1515', 'midas', null, true
 where not exists (select 1 from public.locations where store_number = '1515');

update public.locations
   set is_home_office = true, district_id = null, horizon_shop_number = null
 where store_number = '1515'
   and not is_home_office;

-- Belt and braces: if a row existed before the trigger learned to skip.
delete from public.location_horizon_slots s
 using public.locations l
 where l.id = s.location_id and l.is_home_office
   and s.current_technician_id is null and not s.ever_used;


-- ---------------------------------------------------------------------
-- 4. THE 'office' POSITION — Home Office only, and only 'office' there
-- ---------------------------------------------------------------------
alter table public.employees drop constraint if exists employees_position_check;
alter table public.employees add constraint employees_position_check
  check (position in ('manager','front','tech','cashier','labor_pct_tech','pitman','hood_tech','office'));

create or replace function public.enforce_position_brand()
returns trigger language plpgsql security definer set search_path = '' as $$
declare b text; ho boolean;
begin
  select brand, is_home_office into b, ho from public.locations where id = new.location_id;
  if ho then
    if new.position <> 'office' then
      raise exception 'position % is not valid for the Home Office (use office)', new.position;
    end if;
  elsif b = 'speedee' then
    if new.position not in ('manager','front','cashier','labor_pct_tech','pitman','hood_tech') then
      raise exception 'position % is not valid for a Speedee store', new.position;
    end if;
  else
    if new.position not in ('manager','front','tech') then
      raise exception 'position % is not valid for a Midas store', new.position;
    end if;
  end if;
  return new;
end;
$$;

-- Salaried office staff (see header).
alter table public.employees drop constraint if exists employees_store_manager_is_manager;
alter table public.employees add constraint employees_store_manager_is_manager
  check (not is_store_manager or position in ('manager','office'));

drop index if exists public.employees_one_store_manager_per_location;
create unique index employees_one_store_manager_per_location
  on public.employees (location_id)
  where is_store_manager and position = 'manager';


-- ---------------------------------------------------------------------
-- 5. ROLLUP EXCLUSION — shipped bodies, one predicate added
-- ---------------------------------------------------------------------
-- _tech_pay_range — from pgw_horizon_slots_38.sql; 1 scope site.
create or replace function public._tech_pay_range(d_from date, d_to date, loc uuid default null)
returns table (
  location_id  uuid,
  labor_sales  numeric,
  labor_cost   numeric,
  flag_hours   numeric,
  hours_worked numeric
)
language sql stable security definer set search_path = '' as $$
  with scope as (
    select l.id
      from public.locations l
     where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office
       and (loc is null or l.id = loc)
  ),
  -- Every day of every WHOLE week the range touches, so the engine sees
  -- complete weeks even when the range does not.
  d as (
    select
      td.location_id                                                as loc_id,
      td.tech_slot_id                                               as slot,
      (td.work_date - (extract(dow from td.work_date)::int))::date  as week_start,
      td.hours_worked                                               as hours,
      td.flag_hours                                                 as flag,
      td.labor_sales                                                as labor,
      td.hours_worked * coalesce(r.guarantee_rate, 0)               as guar_pay,
      td.flag_hours   * coalesce(r.flat_rate, 0)                    as commission,
      coalesce(r.guarantee_rate, 0)                                 as guar_rate,
      (td.work_date >= d_from and td.work_date <= d_to)             as in_range
    from public.tech_daily td
    join scope s on s.id = td.location_id
    left join lateral (
      select pr.flat_rate, pr.guarantee_rate
        from public.tech_pay_rates pr
       where pr.employee_id = td.employee_id
         and pr.effective_date <= td.work_date
       order by pr.effective_date desc
       limit 1
    ) r on true
    -- The WHOLE weeks the range touches: Sunday on-or-before d_from
    -- through Saturday on-or-after d_to.
    where td.work_date >= (d_from - (extract(dow from d_from)::int))
      and td.work_date <= (d_to + (6 - extract(dow from d_to)::int))
  ),
  per_week as (
    select
      d.loc_id, d.slot, d.week_start,
      sum(d.hours)                                          as ht,
      sum(d.guar_pay)                                       as gt,
      sum(d.commission)                                     as ct,
      max(d.guar_rate)                                      as gr,
      sum(d.hours) filter (where d.in_range)                as hours_in_range,
      sum(d.labor) filter (where d.in_range)                as labor_in_range,
      sum(d.flag)  filter (where d.in_range)                as flag_in_range
    from d
    group by d.loc_id, d.slot, d.week_start
  ),
  paid as (
    select
      pw.*,
      coalesce(tw.other_pay, 0) as op,
      -- Whole-week overtime. Below 40 hours there is none, by definition.
      case when pw.ht < 40 then 0
           when pw.gt > pw.ct then (pw.ht - 40) * pw.gr * 0.5
           else (pw.ht - 40) * (pw.ct / nullif(pw.ht, 0)) * 0.5 end as ot
    from per_week pw
    left join public.tech_weekly tw
      on tw.tech_slot_id = pw.slot and tw.week_start = pw.week_start
  ),
  attributed as (
    select
      paid.loc_id,
      coalesce(paid.labor_in_range, 0) as a_labor_sales,
      -- Whole-week pay, pro-rated by the hours inside the range.
      case when paid.ht = 0 then 0
           else (greatest(paid.gt + paid.ot, paid.ct) + paid.op)
                * (coalesce(paid.hours_in_range, 0) / paid.ht)
      end                              as a_labor_cost,
      coalesce(paid.flag_in_range, 0)  as a_flag,
      coalesce(paid.hours_in_range, 0) as a_hours
    from paid
  )
  select attributed.loc_id,
         coalesce(sum(attributed.a_labor_sales), 0),
         coalesce(sum(attributed.a_labor_cost), 0),
         coalesce(sum(attributed.a_flag), 0),
         coalesce(sum(attributed.a_hours), 0)
    from attributed
   group by attributed.loc_id;
$$;

-- _report_tech_daily — from pgw_horizon_slots_38.sql; 1 scope site.
create or replace function public._report_tech_daily(
  d_from date,
  d_to   date,
  p_locs uuid[] default null
)
returns table (
  loc_id        uuid,
  d             date,
  hours_worked  numeric,
  flag_hours    numeric,
  labor_sales   numeric,
  guarantee_pay numeric,
  commission    numeric,
  overtime      numeric,
  other_pay     numeric,
  total_pay     numeric
)
language sql stable security definer set search_path = '' as $fn$
  with scope as (
    select l.id
      from public.locations l
     where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office
       and (p_locs is null or l.id = any(p_locs))
  ),
  -- Every day of every WHOLE Sunday–Saturday week the range touches, so
  -- the 40-hour threshold is always evaluated against a complete week
  -- even when the range cuts one in half.
  raw as (
    select
      td.location_id                                                 as l_id,
      td.tech_slot_id                                                as slot,
      td.work_date                                                   as wd,
      (td.work_date - (extract(dow from td.work_date)::int))::date    as wk,
      td.hours_worked                                                as hours,
      td.flag_hours                                                  as flag,
      td.labor_sales                                                 as labor,
      td.hours_worked * coalesce(r.guarantee_rate, 0)                as guar_pay,
      td.flag_hours   * coalesce(r.flat_rate, 0)                     as comm,
      coalesce(r.guarantee_rate, 0)                                  as guar_rate,
      (td.work_date >= d_from and td.work_date <= d_to)              as in_range
    from public.tech_daily td
    join scope s on s.id = td.location_id
    -- The rate of the person who WORKED the day (migration 29), never
    -- of whoever holds the slot today. Reassigning a slot must not
    -- re-cost history.
    left join lateral (
      select pr.flat_rate, pr.guarantee_rate
        from public.tech_pay_rates pr
       where pr.employee_id = td.employee_id
         and pr.effective_date <= td.work_date
       order by pr.effective_date desc
       limit 1
    ) r on true
    where td.work_date >= (d_from - (extract(dow from d_from)::int))
      and td.work_date <= (d_to   + (6 - extract(dow from d_to)::int))
  ),
  per_week as (
    select raw.l_id, raw.slot, raw.wk,
           sum(raw.hours)     as ht,
           sum(raw.guar_pay)  as gt,
           sum(raw.comm)      as ct,
           max(raw.guar_rate) as gr
      from raw
     group by raw.l_id, raw.slot, raw.wk
  ),
  paid as (
    select pw.l_id, pw.slot, pw.wk, pw.ht, pw.gt, pw.ct,
           coalesce(tw.other_pay, 0) as op,
           -- Below 40 hours there is no overtime, by definition. Above
           -- it, the half-time premium rides on whichever basis the
           -- technician is actually being paid on that week.
           case when pw.ht < 40    then 0
                when pw.gt > pw.ct then (pw.ht - 40) * pw.gr * 0.5
                else (pw.ht - 40) * (pw.ct / nullif(pw.ht, 0)) * 0.5
           end as ot
      from per_week pw
      left join public.tech_weekly tw
        on tw.tech_slot_id = pw.slot and tw.week_start = pw.wk
  )
  select
    raw.l_id,
    raw.wd,
    raw.hours,
    raw.flag,
    raw.labor,
    raw.guar_pay,
    raw.comm,
    case when p.ht = 0 then 0 else p.ot * (raw.hours / p.ht) end,
    case when p.ht = 0 then 0 else p.op * (raw.hours / p.ht) end,
    case when p.ht = 0 then 0
         else (greatest(p.gt + p.ot, p.ct) + p.op) * (raw.hours / p.ht) end
  from raw
  join paid p
    on p.l_id = raw.l_id and p.slot = raw.slot and p.wk = raw.wk
  where raw.in_range;
$fn$;

-- _report_grain — from pgw_horizon_slots_38.sql; 1 scope site.
create or replace function public._report_grain(
  d_from date,
  d_to   date,
  p_locs uuid[] default null
)
returns table (loc_id uuid, d date)
language sql stable security definer set search_path = '' as $fn$
  with scope as (
    select l.id
      from public.locations l
     where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office
       and (p_locs is null or l.id = any(p_locs))
  )
  select k.location_id, k.business_date
    from public.daily_kpi k join scope s on s.id = k.location_id
   where k.business_date between d_from and d_to
  union
  select t.location_id, t.work_date
    from public.tech_daily t join scope s on s.id = t.location_id
   where t.work_date between d_from and d_to
  union
  select c.location_id, c.business_date
    from public.cash_drawer_closeouts c join scope s on s.id = c.location_id
   where c.business_date between d_from and d_to;
$fn$;

-- _report_store_scalars — from pgw_horizon_slots_38.sql; 1 scope site.
create or replace function public._report_store_scalars(
  p_year  int,
  p_month int,
  p_locs  uuid[] default null
)
returns table (
  loc_id        uuid,
  days_open     numeric,
  gp_budget     numeric,
  gold_thr      numeric,
  silver_thr    numeric,
  bronze_thr    numeric,
  py_sales      numeric,
  py_gross      numeric,
  py_cars       numeric
)
language sql stable security definer set search_path = '' as $fn$
  select
    l.id,
    coalesce(b.days_open, v.days_open)::numeric,
    coalesce(b.gp_budget, v.gp_target)::numeric,
    b.gold_threshold,
    b.silver_threshold,
    b.bronze_threshold,
    p.sales,
    p.gross_profit,
    p.cars::numeric
  from public.locations l
  left join public.bonus_monthly_targets b
    on b.location_id = l.id and b.plan_year = p_year and b.month = p_month
  left join public.v_store_monthly_gp_target v
    on v.location_id = l.id and v.goal_year = p_year and v.goal_month = p_month
  left join public.prior_year_actuals p
    on p.location_id = l.id and p.year = p_year - 1 and p.month = p_month
 where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office
   and (p_locs is null or l.id = any(p_locs));
$fn$;

-- report_build — from pgw_adjustments_48.sql; 2 scope sites.
create or replace function public.report_build(
  p_from           date,
  p_to             date,
  p_group_by       text,
  p_measures       text[],
  p_locations      uuid[] default null,
  p_split_by_store boolean default false,
  p_max_rows       int     default 5000,
  p_sort_measure   text    default null,
  p_sort_dir       text    default 'desc',
  p_alt_from       date    default null,
  p_alt_to         date    default null,
  p_alt_measures   text[]  default null
)
returns table (
  bucket_key   text,
  bucket_label text,
  bucket_sort  text,
  store_id     uuid,
  store_label  text,
  is_total     boolean,
  measures     jsonb
)
language plpgsql stable security definer set search_path = '' as $fn$
declare
  v_split  boolean;
  v_bad    text;
  v_rows   int;
  v_cap    int;
  v_afrom  date;
  v_ato    date;
  v_gfrom  date;
  v_gto    date;
  v_year   int;
  v_month  int;
  v_alt    text[];
  v_dir    text;
begin
  if p_from is null or p_to is null or p_from > p_to then
    raise exception 'invalid range % .. %', p_from, p_to using errcode = '22007';
  end if;
  if p_group_by is null
     or p_group_by not in ('day', 'week', 'month', 'store', 'district', 'region') then
    raise exception 'unknown grouping %', coalesce(p_group_by, '(null)') using errcode = '22023';
  end if;
  if p_measures is null or cardinality(p_measures) = 0 then
    raise exception 'no measures requested' using errcode = '22023';
  end if;

  select string_agg(m.k, ', ') into v_bad
    from unnest(p_measures) as m(k)
   where m.k not in (select c.measure_key from public.report_measure_catalog() c);
  if v_bad is not null then
    raise exception 'unknown measure(s): %', v_bad using errcode = '22023';
  end if;

  -- THE RESTRICTION, ENFORCED IN THE QUERY (migration 35, unchanged).
  if coalesce(public.current_user_role(), '') not in ('admin', 'master') then
    select string_agg(c.label, ', ' order by c.sort_order) into v_bad
      from public.report_measure_catalog() c
     where c.restricted and c.measure_key = any(p_measures);
    if v_bad is not null then
      raise exception 'not authorized for measure(s): %', v_bad using errcode = '42501';
    end if;
  end if;

  v_dir := lower(coalesce(p_sort_dir, 'desc'));
  if v_dir not in ('asc', 'desc') then
    raise exception 'sort direction must be asc or desc, got %', p_sort_dir using errcode = '22023';
  end if;
  if p_sort_measure is not null and not (p_sort_measure = any(p_measures)) then
    raise exception 'cannot sort by %, it is not one of the selected measures', p_sort_measure
      using errcode = '22023';
  end if;

  v_alt   := coalesce(p_alt_measures, '{}');
  v_afrom := coalesce(p_alt_from, p_from);
  v_ato   := coalesce(p_alt_to,   p_to);
  if v_afrom > v_ato then
    raise exception 'invalid alternate range % .. %', v_afrom, v_ato using errcode = '22007';
  end if;
  v_gfrom := least(p_from, v_afrom);
  v_gto   := greatest(p_to, v_ato);

  v_year  := extract(year  from p_to)::int;
  v_month := extract(month from p_to)::int;

  v_cap   := least(greatest(coalesce(p_max_rows, 5000), 1), 20000);
  v_split := coalesce(p_split_by_store, false) and p_group_by in ('day', 'week', 'month');

  -- ---- size the answer before computing it (main window only) --------
  if p_group_by in ('store', 'district', 'region') then
    select count(*)::int into v_rows from (
      select distinct
        case p_group_by
          when 'store'    then l.id::text
          when 'district' then coalesce(l.district_id::text, '~unassigned')
          else                 coalesce(dd.region_id::text, '~unassigned')
        end as k
        from public.locations l
        left join public.districts dd on dd.id = l.district_id
       where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office
         and (p_locations is null or l.id = any(p_locations))
    ) q;
  else
    select count(*)::int into v_rows from (
      select distinct
        case p_group_by
          when 'day'  then to_char(g.d, 'YYYY-MM-DD')
          when 'week' then to_char((g.d - (extract(dow from g.d)::int))::date, 'YYYY-MM-DD')
          else             to_char(g.d, 'YYYY-MM')
        end as k,
        case when v_split then g.loc_id else null::uuid end as s
        from public._report_grain(p_from, p_to, p_locations) g
    ) q;
  end if;

  if v_rows > v_cap then
    raise exception
      'That report would return % rows, over the limit of %. Narrow the date range, pick fewer stores, or group by a coarser period.',
      v_rows, v_cap
      using errcode = '54000';
  end if;

  return query
  with scope as (
    select l.id as lid, l.store_number as snum, l.name as sname, l.brand as brnd,
           l.district_id as did, dd.name as dname,
           dd.region_id as rid, rr.name as rname
      from public.locations l
      left join public.districts dd on dd.id = l.district_id
      left join public.regions   rr on rr.id = dd.region_id
     where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office
       and (p_locations is null or l.id = any(p_locations))
  ),
  -- Every month the range touches, so a month grouping gets its own
  -- budget and prior year rather than the last month's.
  months as (
    select extract(year from d)::int as yy, extract(month from d)::int as mm
      from generate_series(date_trunc('month', p_from::timestamp),
                           date_trunc('month', p_to::timestamp),
                           interval '1 month') d
  ),
  scal as (
    select m.yy, m.mm, s.loc_id, s.days_open, s.gp_budget,
           s.gold_thr, s.silver_thr, s.bronze_thr, s.py_sales, s.py_gross, s.py_cars
      from months m
      cross join lateral public._report_store_scalars(m.yy, m.mm, p_locations) s
  ),
  bmap as (
    select g.loc_id as lid, g.d as dd,
      case p_group_by
        when 'day'      then to_char(g.d, 'YYYY-MM-DD')
        when 'week'     then to_char((g.d - (extract(dow from g.d)::int))::date, 'YYYY-MM-DD')
        when 'month'    then to_char(g.d, 'YYYY-MM')
        when 'store'    then s.lid::text
        when 'district' then coalesce(s.did::text, '~unassigned')
        else                 coalesce(s.rid::text, '~unassigned')
      end as bkey,
      case when v_split then g.loc_id else null::uuid end as skey
      from public._report_grain(v_gfrom, v_gto, p_locations) g
      join scope s on s.lid = g.loc_id
  ),
  facts (
    bkey, skey, f_loc, f_date,
    f_ro, f_zdt, f_parts, f_tires, f_supplies, f_disc, f_groupon,
    f_declined, f_capps, f_cdollars, f_cparts, f_ctires, f_entered, f_traded,
    f_hours, f_flag, f_labor, f_guar, f_comm, f_ot, f_other, f_total,
    f_cash, f_checks, f_cards, f_bread, f_sync, f_amfirst, f_koalifi,
    f_snap, f_fleet, f_tireunits, f_alignunits
  ) as (
    select bm.bkey, bm.skey, k.location_id, k.business_date,
      k.ro_count::numeric, k.zero_dollar_tickets::numeric,
      k.sales_parts, k.sales_tires, k.sales_supplies, k.sales_discounts, k.sales_adjustments,
      k.declined_sales, k.credit_apps::numeric, k.credit_dollars,
      k.cost_parts, k.cost_tires,
      case when coalesce(k.ro_count, 0)        <> 0
             or coalesce(k.sales_parts, 0)     <> 0
             or coalesce(k.sales_tires, 0)     <> 0
             or coalesce(k.sales_supplies, 0)  <> 0
             or coalesce(k.sales_discounts, 0) <> 0
             or coalesce(k.sales_adjustments, 0)   <> 0
           then k.business_date else null::date end,
      -- "Traded" is the tic sheet's PACE rule and the bonus rule: a day
      -- with repair orders. It drives every projection below.
      case when coalesce(k.ro_count, 0) <> 0 then k.business_date else null::date end,
      0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric,
      0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric,
      0::numeric, 0::numeric,
      coalesce((select sum(u.units) from public.daily_service_units u
                 join public.service_categories c on c.id = u.service_category_id
                where u.daily_kpi_id = k.id and c.horizon_key = 'kpi_su_tires'), 0)::numeric,
      coalesce((select sum(u.units) from public.daily_service_units u
                 join public.service_categories c on c.id = u.service_category_id
                where u.daily_kpi_id = k.id and c.horizon_key = 'kpi_su_wheel_alignments'), 0)::numeric
      from public.daily_kpi k
      join bmap bm on bm.lid = k.location_id and bm.dd = k.business_date
    union all
    select bm.bkey, bm.skey, t.loc_id, t.d,
      0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric,
      0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, null::date, null::date,
      t.hours_worked, t.flag_hours, t.labor_sales,
      t.guarantee_pay, t.commission, t.overtime, t.other_pay, t.total_pay,
      0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric,
      0::numeric, 0::numeric, 0::numeric, 0::numeric
      from public._report_tech_daily(v_gfrom, v_gto, p_locations) t
      join bmap bm on bm.lid = t.loc_id and bm.dd = t.d
    union all
    select bm.bkey, bm.skey, c.location_id, c.business_date,
      0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric,
      0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, null::date, null::date,
      0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric, 0::numeric,
      c.cash, c.checks, c.cards, c.bread, c.synchrony, c.american_first, c.koalifi, c.snap,
      (select coalesce(sum(case when (e ->> 'amount') ~ '^-?[0-9]+(\.[0-9]+)?$'
                                then (e ->> 'amount')::numeric else 0 end), 0)
         from jsonb_array_elements(c.fleet) e),
      0::numeric, 0::numeric
      from public.cash_drawer_closeouts c
      join bmap bm on bm.lid = c.location_id and bm.dd = c.business_date
  ),
  -- A row lands in the main window, the alt window, or both.
  long as (
    select f.*, w.win
      from facts f
      cross join lateral (
        select 'main'::text as win where f.f_date between p_from and p_to
        union all
        select 'alt'::text  where f.f_date between v_afrom and v_ato
      ) w
  ),
  -- PER STORE first, so a projection is a store's own and a market's is
  -- the sum of its stores'.
  per_store as (
    select long.bkey, long.skey, long.f_loc as loc, long.win,
           sum(long.f_ro)       as ro,
           sum(long.f_parts)    as parts,
           sum(long.f_tires)    as tires,
           sum(long.f_supplies) as supplies,
           sum(long.f_disc)     as disc,
           sum(long.f_groupon)  as groupon,
           sum(long.f_cparts)   as cparts,
           sum(long.f_ctires)   as ctires,
           sum(long.f_labor)    as labor,
           sum(long.f_total)    as total_pay,
           count(distinct long.f_traded)::numeric as traded_days
      from long
     group by long.bkey, long.skey, long.f_loc, long.win
  ),
  -- Each store's own projection, ready to be summed.
  per_store_proj as (
    select ps.bkey, ps.skey, ps.win,
           public.report_pace(
             (ps.labor + ps.parts + ps.tires + ps.supplies + ps.disc + ps.groupon)
             - (ps.total_pay + ps.cparts + ps.ctires),
             ps.traded_days, sc.days_open)                         as p_gp,
           public.report_pace(
             ps.labor + ps.parts + ps.tires + ps.supplies + ps.disc,
             ps.traded_days, sc.days_open)                         as p_sales
      from per_store ps
      left join scal sc
        on sc.loc_id = ps.loc
       and sc.yy = case when p_group_by = 'month' then split_part(ps.bkey, '-', 1)::int else v_year end
       and sc.mm = case when p_group_by = 'month' then split_part(ps.bkey, '-', 2)::int else v_month end
  ),
  proj as (
    select per_store_proj.bkey, per_store_proj.skey, per_store_proj.win,
           grouping(per_store_proj.bkey) as g_b, grouping(per_store_proj.skey) as g_s,
           sum(per_store_proj.p_gp)    as a_proj_gp,
           sum(per_store_proj.p_sales) as a_proj_sales
      from per_store_proj
     group by grouping sets (
       (per_store_proj.bkey, per_store_proj.skey, per_store_proj.win),
       (per_store_proj.skey, per_store_proj.win),
       (per_store_proj.win)
     )
  ),
  agg as (
    select
      long.bkey as bkey, long.skey as skey, long.win as win,
      grouping(long.bkey) as g_b, grouping(long.skey) as g_s,
      coalesce(sum(long.f_ro), 0)        as a_ro,
      coalesce(sum(long.f_zdt), 0)       as a_zdt,
      coalesce(sum(long.f_parts), 0)     as a_parts,
      coalesce(sum(long.f_tires), 0)     as a_tires,
      coalesce(sum(long.f_supplies), 0)  as a_supplies,
      coalesce(sum(long.f_disc), 0)      as a_disc,
      coalesce(sum(long.f_groupon), 0)   as a_groupon,
      coalesce(sum(long.f_declined), 0)  as a_declined,
      coalesce(sum(long.f_capps), 0)     as a_capps,
      coalesce(sum(long.f_cdollars), 0)  as a_cdollars,
      coalesce(sum(long.f_cparts), 0)    as a_cparts,
      coalesce(sum(long.f_ctires), 0)    as a_ctires,
      count(distinct long.f_entered)::numeric as a_days,
      count(distinct long.f_traded)::numeric  as a_traded,
      coalesce(sum(long.f_hours), 0)     as a_hours,
      coalesce(sum(long.f_flag), 0)      as a_flag,
      coalesce(sum(long.f_labor), 0)     as a_labor,
      coalesce(sum(long.f_guar), 0)      as a_guar,
      coalesce(sum(long.f_comm), 0)      as a_comm,
      coalesce(sum(long.f_ot), 0)        as a_ot,
      coalesce(sum(long.f_other), 0)     as a_other,
      coalesce(sum(long.f_total), 0)     as a_total,
      coalesce(sum(long.f_cash), 0)      as a_cash,
      coalesce(sum(long.f_checks), 0)    as a_checks,
      coalesce(sum(long.f_cards), 0)     as a_cards,
      coalesce(sum(long.f_bread), 0)     as a_bread,
      coalesce(sum(long.f_sync), 0)      as a_sync,
      coalesce(sum(long.f_amfirst), 0)   as a_amfirst,
      coalesce(sum(long.f_koalifi), 0)   as a_koalifi,
      coalesce(sum(long.f_snap), 0)      as a_snap,
      coalesce(sum(long.f_fleet), 0)     as a_fleet,
      coalesce(sum(long.f_tireunits), 0) as a_tireunits,
      coalesce(sum(long.f_alignunits), 0) as a_alignunits
      from long
     group by grouping sets ((long.bkey, long.skey, long.win), (long.skey, long.win), (long.win))
  ),
  -- Which stores belong to which bucket. For store/district/region this
  -- is EVERY store in scope, so a store that reported nothing still gets
  -- a row with its budget on it — a district comparison has to be able
  -- to say "this one sent nothing".
  sloc as (
    select distinct bm.bkey as bkey, bm.skey as skey, bm.lid as lid
      from bmap bm
     where p_group_by in ('day', 'week', 'month')
       and bm.dd between p_from and p_to
    union
    select distinct
      case p_group_by
        when 'store'    then s.lid::text
        when 'district' then coalesce(s.did::text, '~unassigned')
        else                 coalesce(s.rid::text, '~unassigned')
      end,
      null::uuid, s.lid
      from scope s
     where p_group_by in ('store', 'district', 'region')
  ),
  sagg as (
    select sloc.bkey as bkey, sloc.skey as skey,
           grouping(sloc.bkey) as g_b, grouping(sloc.skey) as g_s,
           count(*)::numeric              as n_stores,
           sum(sc.days_open)              as s_days_open,
           sum(sc.gp_budget)              as s_budget,
           sum(sc.gold_thr)               as s_gold,
           sum(sc.silver_thr)             as s_silver,
           sum(sc.bronze_thr)             as s_bronze,
           sum(sc.py_sales)               as s_py_sales,
           sum(sc.py_gross)               as s_py_gross,
           sum(sc.py_cars)                as s_py_cars
      from sloc
      left join scal sc
        on sc.loc_id = sloc.lid
       and sc.yy = case when p_group_by = 'month' then split_part(sloc.bkey, '-', 1)::int else v_year end
       and sc.mm = case when p_group_by = 'month' then split_part(sloc.bkey, '-', 2)::int else v_month end
     group by grouping sets ((sloc.bkey, sloc.skey), (sloc.skey), ())
  ),
  units_long as (
    select bm.bkey as bkey, bm.skey as skey,
           grouping(bm.bkey) as g_b, grouping(bm.skey) as g_s,
           sc.horizon_key as hkey,
           coalesce(sum(dsu.units), 0)::numeric as u
      from public.daily_service_units dsu
      join public.daily_kpi k on k.id = dsu.daily_kpi_id
      join bmap bm on bm.lid = k.location_id and bm.dd = k.business_date
      join public.service_categories sc on sc.id = dsu.service_category_id
     where k.business_date between p_from and p_to
       and (('cat_units_' || sc.horizon_key) = any(p_measures)
         or ('cat_pct_'   || sc.horizon_key) = any(p_measures))
     group by grouping sets (
       (bm.bkey, bm.skey, sc.horizon_key),
       (bm.skey, sc.horizon_key),
       (sc.horizon_key)
     )
  ),
  units_obj as (
    select ul.bkey as bkey, ul.skey as skey, ul.g_b as g_b, ul.g_s as g_s,
           jsonb_object_agg('cat_units_' || ul.hkey, ul.u) as o_units,
           jsonb_object_agg('cat_pct_'   || ul.hkey,
             case when coalesce(a.a_ro, 0) = 0 then null else ul.u / a.a_ro end) as o_pct
      from units_long ul
      join agg a
        on a.win = 'main' and a.g_b = ul.g_b and a.g_s = ul.g_s
       and a.bkey is not distinct from ul.bkey
       and a.skey is not distinct from ul.skey
     group by ul.bkey, ul.skey, ul.g_b, ul.g_s
  ),
  -- A BUCKET WITH NO DATA STILL HAS A BUDGET.
  --
  -- Caught in verification: `agg` is built from facts, so a store or
  -- market that entered nothing produced no row at all, and the report
  -- lost not just its (correctly empty) sales but its GP Budget, its
  -- Gold, Silver and Bronze thresholds and its planned days — none of
  -- which depend on anyone entering anything. With one store currently
  -- carrying data, the Month Total GP report would have rendered 35 of
  -- 36 rows completely blank, which is precisely the report somebody
  -- needs when a store has not reported.
  --
  -- The universe of rows is therefore every bucket that has SCALARS, in
  -- both windows, unioned with every bucket that has facts. `aggu`
  -- coalesces the fact sums to zero once, here, so the measure
  -- expressions below stay readable instead of carrying sixty coalesces.
  universe as (
    select sg.bkey as bkey, sg.skey as skey, sg.g_b as g_b, sg.g_s as g_s, w.win as win
      from sagg sg cross join (values ('main'), ('alt')) as w(win)
    union
    select a.bkey, a.skey, a.g_b, a.g_s, a.win from agg a
  ),
  aggu as (
    select u.bkey as bkey, u.skey as skey, u.win as win, u.g_b as g_b, u.g_s as g_s,
      coalesce(a.a_ro, 0) as a_ro,               coalesce(a.a_zdt, 0) as a_zdt,
      coalesce(a.a_parts, 0) as a_parts,         coalesce(a.a_tires, 0) as a_tires,
      coalesce(a.a_supplies, 0) as a_supplies,   coalesce(a.a_disc, 0) as a_disc,
      coalesce(a.a_groupon, 0) as a_groupon,     coalesce(a.a_declined, 0) as a_declined,
      coalesce(a.a_capps, 0) as a_capps,         coalesce(a.a_cdollars, 0) as a_cdollars,
      coalesce(a.a_cparts, 0) as a_cparts,       coalesce(a.a_ctires, 0) as a_ctires,
      coalesce(a.a_days, 0) as a_days,           coalesce(a.a_traded, 0) as a_traded,
      coalesce(a.a_hours, 0) as a_hours,         coalesce(a.a_flag, 0) as a_flag,
      coalesce(a.a_labor, 0) as a_labor,         coalesce(a.a_guar, 0) as a_guar,
      coalesce(a.a_comm, 0) as a_comm,           coalesce(a.a_ot, 0) as a_ot,
      coalesce(a.a_other, 0) as a_other,         coalesce(a.a_total, 0) as a_total,
      coalesce(a.a_cash, 0) as a_cash,           coalesce(a.a_checks, 0) as a_checks,
      coalesce(a.a_cards, 0) as a_cards,         coalesce(a.a_bread, 0) as a_bread,
      coalesce(a.a_sync, 0) as a_sync,           coalesce(a.a_amfirst, 0) as a_amfirst,
      coalesce(a.a_koalifi, 0) as a_koalifi,     coalesce(a.a_snap, 0) as a_snap,
      coalesce(a.a_fleet, 0) as a_fleet,         coalesce(a.a_tireunits, 0) as a_tireunits,
      coalesce(a.a_alignunits, 0) as a_alignunits
      from universe u
      left join agg a
        on a.win = u.win and a.g_b = u.g_b and a.g_s = u.g_s
       and a.bkey is not distinct from u.bkey
       and a.skey is not distinct from u.skey
  ),
  shaped as (
    select a.bkey as bkey, a.skey as skey, a.win as win, a.g_b as g_b, a.g_s as g_s,
      (
        jsonb_build_object(
          'ro_count',              a.a_ro,
          'zero_dollar_tickets',   a.a_zdt,
          'zero_dollar_pct',       case when a.a_ro = 0 then null else a.a_zdt / a.a_ro end,
          'sales_parts',           a.a_parts,
          'sales_tires',           a.a_tires,
          'sales_supplies',        a.a_supplies,
          'sales_discounts',       a.a_disc,
          'sales_groupon',         a.a_groupon,
          'declined_sales',        a.a_declined,
          'credit_apps',           a.a_capps,
          'credit_dollars',        a.a_cdollars,
          'cost_parts',            a.a_cparts,
          'cost_tires',            a.a_ctires,
          'days_with_data',        a.a_days,
          'days_elapsed',          a.a_traded,
          'tech_hours_worked',     a.a_hours,
          'tech_flag_hours',       a.a_flag,
          'tech_labor_sales',      a.a_labor,
          'tech_labor_cost',       a.a_total,
          'tech_guarantee_pay',    a.a_guar,
          'tech_commission',       a.a_comm,
          'tech_overtime',         a.a_ot,
          'tech_other_pay',        a.a_other,
          'tech_proficiency',      case when a.a_hours = 0 then null else a.a_flag / a.a_hours end,
          'tech_elr',              case when a.a_flag  = 0 then null
                                        else (a.a_labor + 0.5 * a.a_groupon) / a.a_flag end,
          'tech_cost_per_sold_hr', case when a.a_flag  = 0 then null else a.a_total / a.a_flag end,
          'drawer_cash',           a.a_cash,
          'drawer_checks',         a.a_checks,
          'drawer_cards',          a.a_cards,
          'drawer_bread',          a.a_bread,
          'drawer_synchrony',      a.a_sync,
          'drawer_american_first', a.a_amfirst,
          'drawer_koalifi',        a.a_koalifi,
          'drawer_snap',           a.a_snap,
          'drawer_fleet',          a.a_fleet
        )
        ||
        jsonb_build_object(
          'sales',           (a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc),
          'total_potential', (a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_declined,
          'capture_rate',
            case when ((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_declined) = 0 then null
                 else (a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc)
                      / ((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_declined) end,
          -- Est / Car is TOTAL POTENTIAL over repair orders, not sales
          -- over cars. With no declined sales recorded, potential IS
          -- sales and the figure would be sales-per-car wearing the
          -- wrong name — so it is NULL, which is what renders blank for
          -- the SpeeDee stores in the sample. FLAGGED for BDC: if
          -- SpeeDee must stay blank even once it records declines, that
          -- is a brand rule and one more condition here.
          'ave_estimate',
            case when a.a_ro = 0 or a.a_declined = 0 then null
                 else ((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_declined) / a.a_ro end,
          'gross_sales',   (a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon,
          'cost_of_sales', a.a_total + a.a_cparts + a.a_ctires,
          'gross_profit',
            ((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon)
            - (a.a_total + a.a_cparts + a.a_ctires),
          'gross_profit_pct',
            case when ((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon) = 0 then null
                 else (((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon)
                       - (a.a_total + a.a_cparts + a.a_ctires))
                      / ((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon) end,
          'tires_per_day', case when a.a_days = 0 then null else a.a_tireunits / a.a_days end
        )
        ||
        jsonb_build_object(
          'store_count',    sg.n_stores,
          'days_open',      sg.s_days_open,
          'days_left',      case when sg.s_days_open is null then null
                                 else greatest(sg.s_days_open - (a.a_traded * coalesce(sg.n_stores, 1)), 0) end,
          'gp_budget',      sg.s_budget,
          'projected_gp',   pr.a_proj_gp,
          'projected_sales',pr.a_proj_sales,
          'pct_of_budget',  case when coalesce(sg.s_budget, 0) = 0 then null
                                 else pr.a_proj_gp / sg.s_budget end,
          'cars_per_store',  case when coalesce(sg.n_stores, 0) = 0 then null else a.a_ro / sg.n_stores end,
          'sales_per_store', case when coalesce(sg.n_stores, 0) = 0 then null
                                  else (a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) / sg.n_stores end,
          'gp_per_store',    case when coalesce(sg.n_stores, 0) = 0 then null
                                  else (((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon)
                                        - (a.a_total + a.a_cparts + a.a_ctires)) / sg.n_stores end,
          'py_sales',        sg.s_py_sales,
          'py_gross_profit', sg.s_py_gross,
          'py_cars',         sg.s_py_cars,
          -- Month-end projection against the FULL prior month: both are
          -- whole-month figures, so no proration is needed or wanted.
          'sales_vs_py',     case when sg.s_py_sales is null then null else pr.a_proj_sales - sg.s_py_sales end,
          'sales_vs_py_pct', case when coalesce(sg.s_py_sales, 0) = 0 then null
                                  else (pr.a_proj_sales - sg.s_py_sales) / sg.s_py_sales end,
          -- Cars per store is MONTH-TO-DATE, so last year is PRORATED to
          -- the same share of the month. Comparing a part-month against
          -- a whole one would show every store collapsing. FLAGGED for
          -- BDC: if the sample compares against the whole prior month
          -- instead, drop the proration factor here.
          -- FIXED in migration 37. When nothing has traded, a_traded is
          -- 0, the proration factor is 0, and this collapsed to 0 - 0 = 0
          -- — a market that reported nothing claiming parity with a real
          -- prior year. The helper returns NULL for that case instead.
          'cars_per_store_vs_py',
            public.report_cars_vs_prior_year(
              a.a_ro, sg.n_stores, sg.s_py_cars, a.a_traded, sg.s_days_open)
        )
        ||
        jsonb_build_object(
          'gp_budget_remaining', case when sg.s_budget is null then null
            else sg.s_budget - (((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon)
                                - (a.a_total + a.a_cparts + a.a_ctires)) end,
          'gp_budget_per_day',   case when sg.s_budget is null then null else
            public.report_remaining_per_day(
              sg.s_budget - (((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon)
                             - (a.a_total + a.a_cparts + a.a_ctires)),
              sg.s_days_open, a.a_traded, sg.n_stores) end,
          'gold_threshold',   sg.s_gold,
          'gold_remaining',   case when sg.s_gold is null then null
            else sg.s_gold - (((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon)
                              - (a.a_total + a.a_cparts + a.a_ctires)) end,
          'gold_per_day',     case when sg.s_gold is null then null else
            public.report_remaining_per_day(
              sg.s_gold - (((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon)
                           - (a.a_total + a.a_cparts + a.a_ctires)),
              sg.s_days_open, a.a_traded, sg.n_stores) end,
          'silver_threshold', sg.s_silver,
          'silver_remaining', case when sg.s_silver is null then null
            else sg.s_silver - (((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon)
                                - (a.a_total + a.a_cparts + a.a_ctires)) end,
          'silver_per_day',   case when sg.s_silver is null then null else
            public.report_remaining_per_day(
              sg.s_silver - (((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon)
                             - (a.a_total + a.a_cparts + a.a_ctires)),
              sg.s_days_open, a.a_traded, sg.n_stores) end,
          'bronze_threshold', sg.s_bronze,
          'bronze_remaining', case when sg.s_bronze is null then null
            else sg.s_bronze - (((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon)
                                - (a.a_total + a.a_cparts + a.a_ctires)) end,
          'bronze_per_day',   case when sg.s_bronze is null then null else
            public.report_remaining_per_day(
              sg.s_bronze - (((a.a_labor + a.a_parts + a.a_tires + a.a_supplies + a.a_disc) + a.a_groupon)
                             - (a.a_total + a.a_cparts + a.a_ctires)),
              sg.s_days_open, a.a_traded, sg.n_stores) end
        )
      )
      || coalesce(uo.o_units, '{}'::jsonb)
      || coalesce(uo.o_pct,   '{}'::jsonb) as full_o
      from aggu a
      left join proj pr
        on pr.win = a.win and pr.g_b = a.g_b and pr.g_s = a.g_s
       and pr.bkey is not distinct from a.bkey
       and pr.skey is not distinct from a.skey
      left join sagg sg
        on sg.g_b = a.g_b and sg.g_s = a.g_s
       and sg.bkey is not distinct from a.bkey
       and sg.skey is not distinct from a.skey
      left join units_obj uo
        on a.win = 'main' and uo.g_b = a.g_b and uo.g_s = a.g_s
       and uo.bkey is not distinct from a.bkey
       and uo.skey is not distinct from a.skey
  ),
  -- Main-window values for every measure except those the caller marked
  -- as alt-window, which come from the alt shape instead.
  picked as (
    select m.bkey as bkey, m.skey as skey, m.g_b as g_b, m.g_s as g_s,
      coalesce((select jsonb_object_agg(e.key, e.value)
                  from jsonb_each(m.full_o) e
                 where e.key = any(p_measures) and not (e.key = any(v_alt))), '{}'::jsonb)
      ||
      coalesce((select jsonb_object_agg(e.key, e.value)
                  from jsonb_each(al.full_o) e
                 where e.key = any(v_alt)), '{}'::jsonb) as obj
      from shaped m
      left join shaped al
        on al.win = 'alt' and al.g_b = m.g_b and al.g_s = m.g_s
       and al.bkey is not distinct from m.bkey
       and al.skey is not distinct from m.skey
     where m.win = 'main'
  ),
  keys as (
    select distinct bm.bkey as bkey, bm.skey as skey
      from bmap bm
     where p_group_by in ('day', 'week', 'month')
       and bm.dd between p_from and p_to
    union
    select distinct
      case p_group_by
        when 'store'    then s.lid::text
        when 'district' then coalesce(s.did::text, '~unassigned')
        else                 coalesce(s.rid::text, '~unassigned')
      end,
      null::uuid
      from scope s
     where p_group_by in ('store', 'district', 'region')
  ),
  bmeta as (
    select s.lid::text as bkey,
           '#' || s.snum || ' · ' || s.sname as blabel,
           s.snum as bsort
      from scope s where p_group_by = 'store'
    union all
    select distinct coalesce(s.did::text, '~unassigned'),
           coalesce(s.dname, 'Unassigned'),
           coalesce(s.dname, 'zzzz')
      from scope s where p_group_by = 'district'
    union all
    select distinct coalesce(s.rid::text, '~unassigned'),
           coalesce(s.rname, 'Unassigned'),
           coalesce(s.rname, 'zzzz')
      from scope s where p_group_by = 'region'
  ),
  labelled as (
    select k.bkey as bkey, k.skey as skey,
      case p_group_by
        when 'day'   then to_char(to_date(k.bkey, 'YYYY-MM-DD'), 'MM/DD/YYYY')
        when 'week'  then to_char(to_date(k.bkey, 'YYYY-MM-DD'), 'MM/DD')
                          || ' – ' || to_char(to_date(k.bkey, 'YYYY-MM-DD') + 6, 'MM/DD/YYYY')
        when 'month' then to_char(to_date(k.bkey, 'YYYY-MM'), 'Mon YYYY')
        else bm.blabel
      end as blabel,
      coalesce(bm.bsort, k.bkey) as bsort
      from keys k
      left join bmeta bm on bm.bkey = k.bkey
  ),
  emitted as (
    select l.bkey as o_key, l.blabel as o_label, l.bsort as o_sort,
           l.skey as o_store, sc.sname as o_store_label,
           false as o_total, coalesce(p.obj, '{}'::jsonb) as o_obj
      from labelled l
      left join picked p
        on p.g_b = 0 and p.g_s = 0
       and p.bkey = l.bkey
       and p.skey is not distinct from l.skey
      left join scope sc on sc.lid = l.skey
    union all
    select '~total', 'TOTAL', '~~1', p.skey, sc.sname, true, p.obj
      from picked p
      left join scope sc on sc.lid = p.skey
     where v_split and p.g_b = 1 and p.g_s = 0 and p.skey is not null
    union all
    select '~total', 'TOTAL', '~~2', null::uuid, null::text, true, p.obj
      from picked p
     where p.g_b = 1 and p.g_s = 1
  )
  select e.o_key::text, e.o_label::text, e.o_sort::text,
         e.o_store::uuid, e.o_store_label::text, e.o_total::boolean, e.o_obj::jsonb
    from emitted e
   order by
     e.o_total,
     e.o_store_label nulls first,
     -- The sort IS the message. A row with no value for the sort measure
     -- goes last in both directions: a blank is not a zero and does not
     -- belong at either end of a ranking.
     case when p_sort_measure is not null and v_dir = 'asc'
          then (e.o_obj ->> p_sort_measure)::numeric end asc nulls last,
     case when p_sort_measure is not null and v_dir = 'desc'
          then (e.o_obj ->> p_sort_measure)::numeric end desc nulls last,
     e.o_sort, e.o_key;
end;
$fn$;

-- dashboard_range_metrics — from pgw_dashboard_gp_adjustments_49.sql; 1 scope site.
create or replace function public.dashboard_range_metrics(d_from date, d_to date, loc uuid default null)
returns table (
  store_count       int,
  gross_sales       numeric,
  labor_sales       numeric,
  labor_cost        numeric,
  parts_cost        numeric,
  tire_cost         numeric,
  cost_of_sales     numeric,
  gross_profit      numeric,
  gross_profit_pct  numeric,
  groupon           numeric,
  tire_units        numeric,
  days_with_data    int,
  tires_per_day     numeric,
  credit_apps       numeric,
  ro_count          numeric
)
language plpgsql stable security definer set search_path = '' as $$
declare
  -- BIGINT, not uuid. service_categories and daily_kpi both use
  -- `bigint generated always as identity` (migration 18); only the
  -- location/employee tables are uuid-keyed. Declaring this uuid made
  -- the whole function fail with "invalid input syntax for type uuid".
  v_tire_cat bigint;
begin
  if d_from is null or d_to is null or d_from > d_to then
    raise exception 'invalid range % .. %', d_from, d_to using errcode = '22007';
  end if;
  if loc is not null and not public.can_access_location(loc) then
    raise exception 'not authorized for location %', loc using errcode = '42501';
  end if;

  select id into v_tire_cat
    from public.service_categories where horizon_key = 'kpi_su_tires' limit 1;

  return query
  with scope as (
    select l.id from public.locations l
     where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office
       and (loc is null or l.id = loc)
  ),
  k as (
    select dk.*
      from public.daily_kpi dk
      join scope s on s.id = dk.location_id
     where dk.business_date >= d_from and dk.business_date <= d_to
  ),
  -- A day the store actually traded, not merely a row that exists.
  --
  -- Every column below is QUALIFIED with its table alias on purpose. In
  -- plpgsql an OUT parameter is a variable, and this function has OUT
  -- parameters called ro_count, credit_apps, tire_units and others; a
  -- bare reference matching one of them raises 42702 or, worse, reads
  -- the variable instead of the column. Same trap noted in migration 32.
  entered as (
    select distinct k.business_date
      from k
     where coalesce(k.ro_count, 0) <> 0
        or coalesce(k.sales_parts, 0) <> 0
        or coalesce(k.sales_tires, 0) <> 0
        or coalesce(k.sales_supplies, 0) <> 0
        or coalesce(k.sales_discounts, 0) <> 0
        or coalesce(k.sales_adjustments, 0) <> 0
  ),
  kpi as (
    select
      coalesce(sum(k.sales_parts), 0)     as parts,
      coalesce(sum(k.sales_tires), 0)     as tires,
      coalesce(sum(k.sales_supplies), 0)  as supplies,
      coalesce(sum(k.sales_adjustments), 0)   as k_groupon,
      coalesce(sum(k.sales_discounts), 0) as discounts,
      coalesce(sum(k.cost_parts), 0)      as k_parts_cost,
      coalesce(sum(k.cost_tires), 0)      as k_tire_cost,
      -- ::numeric is NOT cosmetic. credit_apps, ro_count and units are
      -- int columns, so sum() returns BIGINT. Two things go wrong without
      -- the cast: the row fails to match this function's numeric result
      -- type, and — far worse — `tire_units / days_with_data` below
      -- becomes INTEGER DIVISION. 95 tires over 9 days would silently
      -- report 10 instead of 10.56, and nothing would look broken.
      coalesce(sum(k.credit_apps), 0)::numeric as k_credit_apps,
      coalesce(sum(k.ro_count), 0)::numeric    as k_ro_count
    from k
  ),
  units as (
    select coalesce(sum(dsu.units), 0)::numeric as k_tire_units
      from public.daily_service_units dsu
      join k on k.id = dsu.daily_kpi_id
     where v_tire_cat is not null and dsu.service_category_id = v_tire_cat
  ),
  tech as (
    select coalesce(sum(t.labor_sales), 0) as t_labor_sales,
           coalesce(sum(t.labor_cost), 0)  as t_labor_cost
      from public._tech_pay_range(d_from, d_to, loc) t
  ),
  agg as (
    select
      (select count(*)::int from scope)   as n_stores,
      (select count(*)::int from entered) as n_days,
      kpi.*, units.k_tire_units, tech.t_labor_sales, tech.t_labor_cost
    from kpi, units, tech
  )
  select
    -- EVERY column is cast explicitly. RETURNS TABLE matches by position
    -- AND by type, and the inference here is not obvious: sum() over an
    -- int column yields BIGINT, count() yields bigint, and a CASE whose
    -- first branch is a bare NULL takes its type from the other branch.
    -- Leaving any of it implicit produces "structure of query does not
    -- match function result type" — an error that names no column, so it
    -- tells you nothing about which one is wrong. Casting all fifteen
    -- costs nothing and removes the guessing.
    agg.n_stores::int,
    -- Tic-sheet Sales: labour + parts + tires + supplies + discounts.
    -- Adjustments are EXCLUDED from Sales (migration 25) and returned
    -- separately (column `groupon`, name kept in migration 48); gross
    -- profit below adds them back.
    -- Discounts are stored signed and added algebraically.
    (agg.t_labor_sales + agg.parts + agg.tires + agg.supplies + agg.discounts)::numeric,
    agg.t_labor_sales::numeric,
    agg.t_labor_cost::numeric,
    agg.k_parts_cost::numeric,
    agg.k_tire_cost::numeric,
    (agg.t_labor_cost + agg.k_parts_cost + agg.k_tire_cost)::numeric,
    -- Gross profit INCLUDING technician labour cost AND Adjustments
    -- (migration 49: the figure managers are paid on, lib/grossProfit.js,
    -- and the Report Builder's). The old pre-labour figure (migration 22)
    -- subtracted only parts and tyres; if this equals that, it is reading
    -- the wrong source.
    (((agg.t_labor_sales + agg.parts + agg.tires + agg.supplies + agg.discounts) + agg.k_groupon) - (agg.t_labor_cost + agg.k_parts_cost + agg.k_tire_cost))::numeric,
    -- GP % is over Sales PLUS Adjustments, as the Report Builder's is, so
    -- the two screens publish one percentage.
    (case when ((agg.t_labor_sales + agg.parts + agg.tires + agg.supplies + agg.discounts) + agg.k_groupon) = 0 then null
          else (((agg.t_labor_sales + agg.parts + agg.tires + agg.supplies + agg.discounts) + agg.k_groupon) - (agg.t_labor_cost + agg.k_parts_cost + agg.k_tire_cost)) / ((agg.t_labor_sales + agg.parts + agg.tires + agg.supplies + agg.discounts) + agg.k_groupon) end)::numeric,
    agg.k_groupon::numeric,
    agg.k_tire_units::numeric,
    agg.n_days::int,
    -- UNITS per day WITH DATA, never dollars and never per calendar day.
    -- 90 tires over 9 traded days reads 10.0; the same 90 spread over a
    -- 31-day August would read 2.9 and be useless on the 12th.
    (case when agg.n_days = 0 then null
          else agg.k_tire_units::numeric / agg.n_days::numeric end)::numeric,
    agg.k_credit_apps::numeric,
    agg.k_ro_count::numeric
  from agg;
end;
$$;

-- payroll_to_sales_range — from pgw_employee_profile_pay_history_56.sql; 6 scope sites.
create or replace function public.payroll_to_sales_range(d_from date, d_to date, loc uuid default null)
returns table (
  window_start      date,
  window_end        date,
  hours_thru        date,
  sales_thru        date,
  wages_non_tech    numeric,
  wages_tech        numeric,
  wages_total       numeric,
  gross_sales       numeric,
  payroll_to_sales  numeric,
  techs_included    boolean,
  store_count       int
)
language plpgsql stable security definer set search_path = '' as $$
declare
  v_techs  boolean;
  v_cut    date;
  v_start  date;
  v_hours  date;
  v_sales  date;
  v_end    date;
  v_non    numeric := 0;
  v_tech   numeric := 0;
  v_gross  numeric := 0;
begin
  if d_from is null or d_to is null or d_from > d_to then
    raise exception 'invalid range % .. %', d_from, d_to using errcode = '22007';
  end if;
  if loc is not null and not public.can_access_location(loc) then
    raise exception 'not authorized for location %', loc using errcode = '42501';
  end if;

  select include_technicians, daily_cutover_date into v_techs, v_cut
    from public.payroll_config where id;

  -- Daily hours begin at the cutover; earlier days cannot contribute.
  v_start := greatest(d_from, v_cut);

  window_start   := v_start;
  techs_included := v_techs;
  select count(*)::int into store_count
    from public.locations l
   where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office and (loc is null or l.id = loc);

  if v_start > d_to then
    window_end := null; hours_thru := null; sales_thru := null;
    wages_non_tech := null; wages_tech := null; wages_total := null;
    gross_sales := null; payroll_to_sales := null;
    return next; return;
  end if;

  select max(pd.work_date) into v_hours
    from public.payroll_daily pd
    join public.employees e on e.id = pd.employee_id
    join public.locations l on l.id = pd.location_id
   where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office and (loc is null or l.id = loc)
     and not e.is_store_manager
     and pd.work_date >= v_start and pd.work_date <= d_to
     and (pd.hours_worked + pd.hours_worked_other) > 0;

  select greatest(v_hours, max(td.work_date)) into v_hours
    from public.tech_daily td
    join public.locations l on l.id = td.location_id
   where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office and (loc is null or l.id = loc)
     and td.employee_id is not null
     and td.work_date >= v_start and td.work_date <= d_to
     and td.hours_worked > 0;

  select max(dk.business_date) into v_sales
    from public.daily_kpi dk
    join public.locations l on l.id = dk.location_id
   where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office and (loc is null or l.id = loc)
     and dk.business_date >= v_start and dk.business_date <= d_to
     and (coalesce(dk.ro_count, 0) <> 0
          or coalesce(dk.sales_parts, 0) <> 0
          or coalesce(dk.sales_tires, 0) <> 0
          or coalesce(dk.sales_supplies, 0) <> 0
          or coalesce(dk.sales_discounts, 0) <> 0);

  -- NOT least(): SQL's LEAST ignores nulls and would return the other
  -- bound, so a side with no data at all would silently not constrain
  -- the window. If either side is empty there is no overlap.
  if v_hours is null or v_sales is null then
    v_end := null;
  else
    v_end := least(v_hours, v_sales);
  end if;

  window_end := v_end;
  hours_thru := v_hours;
  sales_thru := v_sales;

  if v_end is null or v_end < v_start then
    wages_non_tech := null; wages_tech := null; wages_total := null;
    gross_sales := null; payroll_to_sales := null;
    return next; return;
  end if;

  -- ---- non-technician wages, whole-week overtime, pro-rated ---------
  with scope as (
    select l.id from public.locations l
     where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office and (loc is null or l.id = loc)
  ),
  wk as (
    select
      pd.employee_id,
      (pd.work_date - (extract(dow from pd.work_date)::int))::date as week_start,
      sum(pd.hours_worked + pd.hours_worked_other)                 as week_hours,
      sum(pd.hours_turned)                                         as week_turned,
      sum((pd.hours_worked + pd.hours_worked_other))
        filter (where pd.work_date >= v_start and pd.work_date <= v_end) as hours_in,
      sum(pd.hours_turned)
        filter (where pd.work_date >= v_start and pd.work_date <= v_end) as turned_in
    from public.payroll_daily pd
    join scope s on s.id = pd.location_id
    join public.employees e on e.id = pd.employee_id
   where not e.is_store_manager
     and pd.work_date >= (v_start - (extract(dow from v_start)::int))
     and pd.work_date <= (v_end + (6 - extract(dow from v_end)::int))
   group by pd.employee_id, (pd.work_date - (extract(dow from pd.work_date)::int))::date
  )
  select coalesce(sum(
    case when wk.week_hours = 0 then 0
         else greatest(
                coalesce(r.hourly_rate, 0) * least(wk.week_hours, 40)
                  + coalesce(r.hourly_rate, 0) * 1.5 * greatest(wk.week_hours - 40, 0),
                coalesce(r.flat_rate_per_hour, 0) * wk.week_turned)
              * (coalesce(wk.hours_in, 0) / wk.week_hours)
    end), 0)
    into v_non
    from wk
    left join lateral public._pay_rate_at(wk.employee_id, wk.week_start) r on true;

  -- ---- technician wages, from the engine, already whole-week --------
  if v_techs then
    select coalesce(sum(t.labor_cost), 0) into v_tech
      from public._tech_pay_range(v_start, v_end, loc) t;
  else
    v_tech := 0;
  end if;

  -- ---- denominator: the tic sheet's own Sales ------------------------
  select coalesce(sum(
           coalesce(lab.labor, 0) + coalesce(k.sales_parts, 0) + coalesce(k.sales_tires, 0)
           + coalesce(k.sales_supplies, 0) + coalesce(k.sales_discounts, 0)), 0)
    into v_gross
    from public.locations l
    left join public.daily_kpi k
           on k.location_id = l.id and k.business_date >= v_start and k.business_date <= v_end
    left join lateral (
      select sum(td.labor_sales) as labor
        from public.tech_daily td
       where td.location_id = l.id and td.work_date = k.business_date
    ) lab on true
   where public.can_access_location(l.id) and l.is_sandbox = false and not l.is_home_office and (loc is null or l.id = loc);

  wages_non_tech   := v_non;
  wages_tech       := v_tech;
  wages_total      := v_non + v_tech;
  gross_sales      := v_gross;
  payroll_to_sales := case when v_gross = 0 then null else (v_non + v_tech) / v_gross end;
  return next;
end;
$$;


-- ---------------------------------------------------------------------
-- 6. DIRECTORY — the Home Office is not listed (migration 59 body)
-- ---------------------------------------------------------------------
create or replace function public.directory_stores()
returns table (
  location_id   uuid,
  store_number  text,
  name          text,
  brand         text,
  shop_number   text,
  region_id     uuid,
  region_name   text,
  district_id   uuid,
  district_name text,
  address_line1 text,
  address_line2 text,
  city          text,
  state         text,
  postal_code   text,
  main_phone    text,
  marchex_phone text,
  store_email   text,
  services      jsonb
)
language sql stable security definer set search_path = '' as $$
  select l.id, l.store_number, l.name, l.brand, l.horizon_shop_number,
         r.id, r.name, d.id, d.name,
         l.address_line1, l.address_line2, l.city, l.state, l.postal_code,
         l.main_phone, l.marchex_phone, l.store_email,
         coalesce(
           (select jsonb_agg(jsonb_build_object('code', st.code, 'label', st.label)
                             order by st.sort_order, st.label)
              from public.location_service_types lst
              join public.service_types st on st.id = lst.service_type_id
             where lst.location_id = l.id and st.active),
           '[]'::jsonb)
    from public.locations l
    left join public.districts d on d.id = l.district_id
    left join public.regions   r on r.id = d.region_id
   where not l.is_sandbox
     and not l.is_home_office
     and auth.uid() is not null
   order by r.name nulls last, d.name nulls last, l.store_number nulls last, l.name;
$$;


-- ---------------------------------------------------------------------
-- CONFIRMATIONS (run after applying)
-- ---------------------------------------------------------------------
--  1) select store_number, name, brand, district_id, is_home_office, is_sandbox, horizon_shop_number
--       from public.locations where is_home_office;
--     Expect one row: 1515, Home Office, midas, null, true, false, null.
--  2) select count(*) from public.location_horizon_slots s
--       join public.locations l on l.id = s.location_id where l.is_home_office;
--     Expect 0.
--  3) select p.proname from pg_proc p
--      where p.pronamespace = 'public'::regnamespace
--        and p.prosrc like '%is_sandbox = false%'
--        and p.prosrc not like '%not l.is_home_office%';
--     Expect 0 rows.
--  4) select prosrc like '%not l.is_home_office%' from pg_proc
--      where proname = 'directory_stores' and pronamespace = 'public'::regnamespace;
--     Expect true.
--  5) Master sign-in: pick "#1515 — Home Office". The menu shows Payroll,
--     Schedule, Documents, Training, Directory (+ Reports/Users); the
--     Payroll page offers only the Office position.
