import ExcelJS from "exceljs";
import { downloadWorkbook } from "./excelStyle.js";
import { RULES, excelRules } from "./scorecardRules.js";

// =====================================================================
// Matt's reports, Phase 1: the Excel export ("Current Month" tab).
//
// Laid out in HIS columns, so a cell sits where he expects it: Report 1
// in A–AD from row 7, Report 2 below it, Report 5 below that. Calibri 12,
// bold store names, the store-name cell filled with its market colour.
//
// COLOURS ARE LIVE RULES (the user, 2026-09-21): every coloured column
// gets conditional-formatting rules generated by scorecardRules.js from
// the same description the screen uses, each comparing the cell with its
// own row's goal cell. Edit a number or a goal in the file and Excel
// recolours it. The helper goals a rule reads (Car Goal Today, the
// market's daily tiers) are written into their own labelled columns so
// the rule has a cell to point at.
//
// Loaded on demand (ScorecardView imports this file dynamically) so
// ExcelJS stays off the first page load.
// =====================================================================

const CUR = '"$"#,##0';
const PCT = "0%";
const DEC1 = "0.0";
const INT = "#,##0";
const FONT = { name: "Calibri", size: 12 };

// Report 1: key -> [column, header, format]. Matt's letters.
const R1 = {
  dailyGp: ["A", "Daily GP", CUR], dailyGold: ["B", "Daily Gold", CUR], dailySilver: ["C", "Daily Silver", CUR],
  dailyBronze: ["D", "Daily Bronze", CUR], dailySales: ["E", "Daily Sales Budget", CUR], name: ["F", "Store", null],
  cars: ["G", "Cars", INT], estPerCar: ["I", "Est/Car", CUR], aro: ["J", "ARO", CUR], capture: ["K", "Sales Capture %", PCT],
  battery: ["L", "Battery Contest MTD", INT], sales: ["M", "Sales", CUR], gp: ["O", "Total GP $", CUR], gpPct: ["P", "Total GP%", PCT],
  mtdSales: ["Q", "MTD Sales", CUR], mtdGp: ["R", "MTD GP", CUR], projGp: ["S", "Projected Monthly GP", CUR],
  salesBudget: ["T", "Sales Budget", CUR], salesProj: ["U", "Sales Projection", CUR], pctOfGoal: ["V", "% of goal", PCT],
  pySales: ["W", "2025 Sales", CUR], vs2025: ["X", "vs 2025", CUR], gpBudget: ["Y", "GP Budget", CUR],
  goldGp: ["Z", "Gold GP", CUR], silverGp: ["AA", "Silver GP", CUR], bronzeGp: ["AB", "Bronze GP", CUR],
  salesGoalToday: ["AD", "Sales Goal Today", CUR], carGoalToday: ["AF", "Car Goal Today", DEC1],
};
// Report 2 (Matt's rows 50–56 use the same letters where he had them).
const R2 = {
  gpBudget: ["E", "GP Budget", CUR], name: ["F", "Market", null],
  carsPerDayPerStore: ["H", "MTD Cars/Day per Store", DEC1], carsVs2025: ["I", "Cars vs 2025", DEC1],
  weeklyGoalPerStore: ["J", "Weekly Goal per Store", CUR], weeklyProjPerStore: ["K", "Weekly Projection per Store", CUR],
  weeklyProjVs2025: ["L", "Projection vs 2025", PCT], gpYesterdayPerStore: ["M", "Daily GP $ Yesterday per Store", CUR],
  pctOfBudget: ["O", "% of Budget", PCT], projGp: ["P", "Projected Monthly GP", CUR], goldGp: ["Q", "Gold", CUR],
  silverGp: ["R", "Silver", CUR], bronzeGp: ["S", "Bronze", CUR], pctToBudget: ["Y", "% to Budget", PCT],
  bonusPct: ["AA", "Proj Bonus % of Salary", PCT],
  dailyBudgetPerStore: ["AC", "Daily Budget/Store", CUR], dailyGoldPerStore: ["AD", "Daily Gold/Store", CUR],
  dailySilverPerStore: ["AE", "Daily Silver/Store", CUR], dailyBronzePerStore: ["AF", "Daily Bronze/Store", CUR],
};
// Report 5 (Matt's rows 61–100).
const R5 = {
  pySold: ["B", "2025 Sold", INT], mtd: ["C", "MTD", INT], monthGoal: ["D", "Month Tire Goal", INT], dailyGoal: ["E", "Daily Goal", DEC1],
  name: ["F", "Store", null], tiresYest: ["G", "Tires Yest", INT], alignYest: ["I", "Align Yest", INT],
  tiresPerDay: ["M", "Monthly Tires/Day", DEC1], mtdProjection: ["O", "MTD Projection", INT], projVsLy: ["P", "Projection vs LY", INT],
  payout: ["Q", "AM Payout", CUR], vs2025: ["R", "Sales PROJ vs 25", CUR], carsVs2025: ["S", "Cars/Day vs 2025", DEC1],
};

const WIDTH = { F: 13.4, A: 10, B: 10, C: 10, D: 10, E: 11, G: 7, I: 8, J: 8, K: 8, L: 8, M: 10, O: 10, P: 7, Q: 12, R: 11,
  S: 12, T: 12, U: 12, V: 7, W: 12, X: 11, Y: 11, Z: 11, AA: 11, AB: 11, AD: 11, AF: 10, H: 7, AC: 11, AE: 11 };

function writeBlock(ws, map, rows, footer, startRow, { report, settings, title }) {
  ws.getCell(`F${startRow - 1}`).value = title;
  ws.getCell(`F${startRow - 1}`).font = { ...FONT, bold: true, size: 13 };
  const header = ws.getRow(startRow);
  for (const [, [c, label]] of Object.entries(map)) {
    const cell = header.getCell(c);
    cell.value = label;
    cell.font = { ...FONT, bold: true };
    cell.alignment = { wrapText: true, vertical: "bottom", horizontal: "center" };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFEDEDED" } };
  }
  header.height = 32;
  const first = startRow + 1;
  const put = (r, rowIdx, bold) => {
    const row = ws.getRow(rowIdx);
    for (const [key, [c, , fmt]] of Object.entries(map)) {
      const cell = row.getCell(c);
      const v = r[key];
      cell.value = key === "name" ? r.name : (v === null || v === undefined ? null : v);
      cell.font = { ...FONT, bold: bold || key === "name" };
      if (fmt) cell.numFmt = fmt;
      if (key === "name" && r.fill && !r.isTotal) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF" + r.fill } };
        cell.font = { ...FONT, bold: true, color: { argb: "FF" + (r.font ?? "000000") } };
      }
    }
  };
  rows.forEach((r, i) => put(r, first + i, false));
  const last = first + rows.length - 1;
  footer.forEach((r, i) => put(r, last + 1 + i, true));

  // Live rules on the data rows (not the totals), from the shared engine.
  const colOf = (k) => map[k]?.[0] ?? null;
  if (rows.length) {
    for (const key of Object.keys(RULES[report])) {
      const spec = excelRules(report, key, { colOf, firstRow: first, lastRow: last, settings });
      if (!spec || !spec.rules.length) continue;
      ws.addConditionalFormatting({
        ref: spec.ref,
        rules: spec.rules.map(({ token, ...rule }, i) => ({ ...rule, priority: i + 1 })),
      });
    }
  }
  return last + footer.length;
}

export function buildScorecardWorkbook({ built, reportDate, ctx }) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "PGW Support Portal";
  const ws = wb.addWorksheet("Current Month", { views: [{ state: "frozen", xSplit: 6, ySplit: 6 }] });
  for (const [c, w] of Object.entries(WIDTH)) ws.getColumn(c).width = w;

  // Matt's header cells: G2 days open so far, Q2 days this month.
  ws.getCell("F1").value = `Current Month — report date ${reportDate}`;
  ws.getCell("F1").font = { ...FONT, bold: true, size: 14 };
  ws.getCell("F2").value = "Days Open"; ws.getCell("G2").value = ctx.elapsed;
  ws.getCell("P2").value = "Days This Month"; ws.getCell("Q2").value = ctx.daysOpen;
  for (const a of ["F2", "G2", "P2", "Q2"]) ws.getCell(a).font = { ...FONT, bold: true };

  const settings = built.settings;
  const r1 = { ...R1 };
  if (built.scorecard.rows.every((r) => !r.battery)) delete r1.battery; // empty column hidden, as on screen
  let end = writeBlock(ws, r1, built.scorecard.rows, [built.scorecard.total, built.scorecard.scTotal].filter(Boolean), 6,
    { report: "scorecard", settings, title: "Daily Scorecard" });

  const r2 = { ...R2 };
  if (!built.hasBonus) delete r2.bonusPct; // admin/master only: never written for anyone else
  const mRows = built.markets.rows.map((m) => ({ ...m, bonusPct: m.bonus?.payoutPct ?? null }));
  const mTotal = { ...built.markets.total, bonusPct: built.markets.total.bonus?.payoutPct ?? null };
  end = writeBlock(ws, r2, mRows, [mTotal], end + 4, { report: "markets", settings, title: "Market Summary" });

  writeBlock(ws, R5, built.tires.rows, [...built.tires.markets, built.tires.total], end + 4,
    { report: "tires", settings, title: "Tire Contest (Midas)" });

  ws.eachRow((row) => row.eachCell((cell) => { if (!cell.font?.name) cell.font = { ...FONT, ...(cell.font ?? {}) }; }));
  return wb;
}

export async function downloadScorecardWorkbook(args) {
  const wb = buildScorecardWorkbook(args);
  const buf = await wb.xlsx.writeBuffer();
  downloadWorkbook(buf, `Current Month ${args.reportDate}.xlsx`);
}
